[package]
name = "tfs"
version = "0.1.0"
authors = ["mental <m3nta1@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
